### ISSUE TITLE
Got following error after npm update

### ISSUE THREAD

**Issue by LIJIOJOHN123** [joaopaulomoraes/nextjs-with-redux-and-material-ui#20]
![image](https://user-images.githubusercontent.com/24985837/121577562-4429a200-ca47-11eb-85c9-894ef751439a.png)

**Comment by joaopaulomoraes** [comment]
It seems to be an error with redux, `npm update` will update all packages and dependencies, in which case there may be some breaking changes.

Tip: The project was built with `yarn`. Prefer to prioritize your tests whenever possible (in this repo) ;)
