### ISSUE TITLE
unable to run code.

### ISSUE THREAD

**Issue by sanjeev89** [joaopaulomoraes/nextjs-with-redux-and-material-ui#29]
![image](https://user-images.githubusercontent.com/35504819/133406383-de81d991-cc85-4e36-98e7-7ee7b28c2d99.png)
![image](https://user-images.githubusercontent.com/35504819/133406598-6934e54b-07d2-4a00-92a5-3675ef383531.png)

something is wrong with the redux-wrapper....getting following errors on console and browser

**Comment by joaopaulomoraes** [comment]
You've probably made major wrapper or even redux updates. Newer versions work a little differently. Try to run the project with the provided libraries, I believe you won't have any problems.

**Comment by 1ET** [comment]
use yarn, do not use npm
